### PR TITLE
Remove boost

### PR DESCRIPTION
**Pull request by chadnickbok**
Use glib functions instead of boost.

Since libnice requires glib we're stuck with it for a while - might as well make use of it.

### CODE REVIEW

**Comment by gegles** [comment]
That's awesome Nick! Thanks for doing that. I would approve, but there is a conflict....

**Comment by chadnickbok** [comment]
Your branch needs to be merged in first.

**Comment by gegles** [comment]
My branch is already merged and part of master.... you may need to rebase..

**Comment by chadnickbok** [comment]
Okay, fixed!

**Pull request merged**
